### ISSUE TITLE
Create a CI/CD documentation website

### ISSUE THREAD

**Issue by William-McGonagle** [SaltyAom/kingworld#4]
I'm working on another bun project and I found that you can get more contributors with a website. I built a really simple website and documentation generation tool if you want to add it to your project. Its under the MIT License- I'm just sending it around the bun community so it gains some more traction. If you want to check it out, it's [right here](https://github.com/William-McGonagle/bun-doc). It's all integrated with Github Actions so all you have to do is add the code to GitHub actions and then you're are all set. If you don't want to, just let me know and close this issue- good luck with your project!

Also, just a tip, add a bunch of issues you need help with and label them "good first issue" because then people will see your project from places like goodfirstissues.com.

**Comment by SaltyAom** [comment]
Thank you for your kind contribution.
Your project looks great, and I would love to use it in the future.

However, for now, I prefer a dedicated manual library to write up documentation like VitePress instead.
Because I would like to have some embed stuff like REPL editor inside the doc, and customizability which I prefers manual way instead for now.
